language: python
python:
- '3.5'
install:
- pip3 install -r requirements.txt
script: python test.py
before_deploy:
- pip3 install Fabric3 gitric
deploy:
  provider: script
  script: fab -H $DEPLOY_HOSTS -p $DEPLOY_PASS prod deploy_from_travis cutover
  on:
    branch: master
