language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: python test.py
before_deploy:
- pip install fabric gitric
deploy:
  provider: script
  script: fab -H $DEPLOY_HOSTS -p $DEPLOY_PASS prod deploy_from_travis cutover
  on:
    branch: master
